---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: sample-app-deployment
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/yoonjaeyol/sampel-app-deployment

